### ISSUE TITLE
Retain cycle in PTURLRequestOperation

### ISSUE THREAD

**Issue by danset** [pusher/libPusher#245] opened 2017-01-24 17:01 UTC
`NSURLSession` retains its delegate until you invalidate it which currently only happens when the operation is cancelled.  There needs to be a call to `finishTasksAndInvalidate` or `invalidateAndCancel` somewhere in the case where the operation finishes executing or it never gets deallocated since the operation and the session are retaining each other.

**Comment by rex-remind101** [comment] 2017-02-21 21:37
Did this fix your issue https://github.com/pusher/libPusher/pull/246 ?

**Comment by lukeredpath** [comment] 2017-02-22 16:08
Sounds like a dupe of #246 to me.

**Closed by lukeredpath** 2017-02-22 16:08 UTC
