### ISSUE TITLE
Does not subscribe to presence channel automatically on connect

### ISSUE THREAD

**Issue by navgoel** [pusher/libPusher#177] opened 2015-04-22 15:29 UTC
Pusher will NOT subscribe to presence channel automatically. Spent quiet some time to figure out what is happening but with no success. Tried different ways to subscribe to channel, like calling "subscribeToPresenceChannelNamed" before reconnect etc. But didnt help. Connect happens when app comes to foreground and disconnect when app goes to background.  The behavior of not able to subscribe to channel automatically is somewhat random and is more easily reproducible on device. i.e. If I am doing background/foreground 5-6 times. I will see that presenceChannelDidSubscribe is not called eventually. I do get connectionDidConnect callback. Also note this is reproducible by normal channel as well. If app is killed and restarted everything is fine. 

Sample Code:
From: applicationWillEnterForeground:

    _pusherClient = [PTPusher pusherWithKey:@"API_KEY" delegate:self encrypted:YES];    
    _pusherClient.authorizationURL = [NSURL URLWithString:@"server/pusher/auth"];    
   [_pusherClient connect];
   
   
Conforming to delegate PTPusherDelegate and in method connectionDidConnect

- (void)pusher:(PTPusher *)pusher connectionDidConnect:(PTPusherConnection *)connection
{
    PTPusherChannel* theChannel = [pusher channelNamed:@"presence-name"];
    if (!theChannel || !theChannel.isSubscribed)
    {
//        theChannel
        [pusher subscribeToPresenceChannelNamed:@"presence-name" delegate:self];
    }
}
    
We also conform to delegate PTPusherPresenceChannelDelegate and we bind to events in presenceChannelDidSubscribe.

Only _pusherClient is a member variable for a singleton class.

**Comment by lukeredpath** [comment] 2015-04-22 15:46
Thanks, I will look into this.

**Comment by navgoel** [comment] 2015-04-24 18:21
sent a sample project to your email if it helps.

**Comment by hamchapman** [comment] 2015-04-28 10:22
We (Pusher) have been in touch with Navin about this and it seems that the issue could be stemming from multiple sockets being opened upon reopening the app once it's been closed.

It seems that the subscribe delegate isn't getting called because of an exception being thrown inside of SocketRocket:

```
2015-04-27 14:42:00.341 DebugPusher[44309:4715485] *** Assertion failure in -[SRWebSocket send:], 
/DebugPusher/Pods/SocketRocket/SocketRocket/SRWebSocket.m:718
2015-04-27 14:42:00.410 DebugPusher[44309:4715485] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid State: Cannot call send: until connection is open'
*** First throw call stack:
(
	0   CoreFoundation                      0x00fd7746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x00c60a97 objc_exception_throw + 44
	2   CoreFoundation                      0x00fd75da +[NSException raise:format:arguments:] + 138
	3   Foundation                          0x008cd720 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
	4   DebugPusher                         0x00029293 -[SRWebSocket send:] + 259
	5   DebugPusher                         0x0003db93 -[PTPusherConnection send:] + 307
	6   DebugPusher                         0x0003513b -[PTPusher sendEventNamed:data:channel:] + 715
	7   DebugPusher                         0x00039120 -[PTPusherChannel subscribeWithAuthorization:] + 304
	8   DebugPusher                         0x00034938 __31-[PTPusher subscribeToChannel:]_block_invoke + 488
	9   DebugPusher                         0x000382e3 -[PTPusherChannel authorizeWithCompletionHandler:] + 179
	10  DebugPusher                         0x000346fb -[PTPusher subscribeToChannel:] + 187
	11  DebugPusher                         0x00034ce6 -[PTPusher subscribeAll] + 374
	12  DebugPusher                         0x000353ea -[PTPusher pusherConnectionDidConnect:] + 266
	13  DebugPusher                         0x0003e348 -[PTPusherConnection webSocket:didReceiveMessage:] + 696
	14  DebugPusher                         0x00029c26 __30-[SRWebSocket _handleMessage:]_block_invoke + 102
	15  libdispatch.dylib                   0x0273d5ea _dispatch_call_block_and_release + 15
	16  libdispatch.dylib                   0x0275fbef _dispatch_client_callout + 14
	17  libdispatch.dylib                   0x027456bb _dispatch_main_queue_callback_4CF + 993
	18  CoreFoundation                      0x00f308ee __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	19  CoreFoundation                      0x00eee5f0 __CFRunLoopRun + 2256
	20  CoreFoundation                      0x00eeda5b CFRunLoopRunSpecific + 443
	21  CoreFoundation                      0x00eed88b CFRunLoopRunInMode + 123
	22  GraphicsServices                    0x03b262c9 GSEventRunModal + 192
	23  GraphicsServices                    0x03b26106 GSEventRun + 104
	24  UIKit                               0x01396106 UIApplicationMain + 1526
	25  DebugPusher                         0x0002507a main + 138
	26  libdyld.dylib                       0x0278aac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

It occurs in this part of the code:
```objective-c
- (void)send:(id)data;
{
    NSAssert(self.readyState != SR_CONNECTING, @"Invalid State: Cannot call send: until connection is open");
...
```

and it seems to be that when the app is reopened and multiple sockets are opened, and a connection established, then you get an error in the Pusher Debug Console (and in Xcode) saying that a subscription to the channel has already been made. If you then close the app and relaunch it then this is when the exception seems to get thrown because for whatever reason there are now two sockets and both of them are instructed to send a `pusher:subscribe` message, however, only one of them has a `readyState` equal to 1 (i.e. `SR_OPEN` in SocketRocket), and then other has `readyState` equal to 0 (i.e. `SR_CONNECTING`).

This seems to happen with not only presence channels but with all types of channels. 

I should note that this has also only occurred for me while testing on a physical device (iPhone 6 in my case). I'm unable to reproduce the error in the Simulator.

Let me know if there's anything else we can do to help out with debugging this.

**Comment by lukeredpath** [comment] 2015-04-28 10:30
Interesting, thanks. 

I wonder if explicitly disconnecting when the app goes to the background is the right thing to do here. Perhaps it should just be left for the system to kill the socket. 

The library should detect the disconnection on relaunch and automatically reconnect and fire it's delegate callbacks. 

Worth experimenting with but I will investigate this when I get the chance.

**Comment by hamchapman** [comment] 2015-04-28 11:13
I've removed the explicit disconnect and this seems to work in terms of always resubscribing. 

So in that sense it is a solution, however, when the app is backgrounded the socket remains open for approximately 4-5 minutes (I tested 3 times and it always fell in that range) before being closed, at which point the connection to pusher is closed and the channel vacated. So if a user wants to know when an app has been backgrounded (and therefore may make a call to disconnect) with the expectation of getting a `member_removed` webhook or presence event, then they won't. I suppose unsubscribing might work in that case - I'll give this a try later today).

In terms of forcefully closing the app, through the multitasking view - this forces the socket to close and re-subscription again works upon re-opening the app.

**Comment by lukeredpath** [comment] 2015-04-28 11:20
@hamchapman if the desired behaviour is for the user to leave a channel when the app goes to the background I do think an explicit unsubscribe would be more appropriate than a full on disconnect. In other words, I feel its better to let the system take care of connection management rather than trying to do it yourself. 

4-5 minutes before disconnecting sounds about right however I would expect the system to terminate this quicker if necessary and it wants to free up resources.

**Comment by navgoel** [comment] 2015-04-28 15:22
@lukeredpath @hamchapman Thanks for looking into this. Not calling disconnect explicitly is fine for time being. But I do think users should be able to disconnect on demand, which is very important for maintaining maximum concurrent connections with Pusher. It allows to free up the unused connection and avoid reaching max allowed connections easily.

Secondly, I am wondering if we should never call disconnect, why this method is exposed and what is it supposed to be used for ?

**Comment by leggetter** [comment] 2015-04-28 23:10
@navgoel 

> I am wondering if we should never call disconnect, why this method is exposed and what is it supposed to be used for ?

it should be possible to call `disconnect`, but it appears that if you do this at reasonably frequent (connect/disconnect) intervals something gets into an unexpected state; exactly the issue you have uncovered.

We'll investigate and fix this. But I'm pleased that we have a workaround for the time being.

**Comment by hamchapman** [comment] 2015-04-29 09:11
I've just tested unsubscribing when the app gets backgrounded and then resubscribing when it gets foregrounded and it works perfectly. 

@navgoel, if you would like me to send the code to you then I can (it's a very simple change though - just unsubscribe instead of disconnect and then make sure to resubscribe when foregrounding the app).

Also, in terms of the maximum number of connections with Pusher, I don't think this should be a problem. As noted, a connection will be cleaned up after 4-5 minutes of the app being backgrounded and so unless you're planning on getting incredibly close to your connection limits on a minute-by-minute basis, I think this should be fine :+1:

**Comment by hamchapman** [comment] 2016-06-29 09:28
Added a note about calling `unsubscribe` as opposed to `disconnect` in the readme: 9138de6

**Closed by hamchapman** 2016-06-29 09:28 UTC
